import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Icon } from '@/components/Icon';
import { deliveries } from '@/src/data';
import { colors } from '@/src/theme';

export default function Envios() {
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.head}><View><Text style={styles.kicker}>ACTIVIDAD</Text><Text style={styles.title}>Mis envíos</Text></View><Pressable style={styles.filter}><Icon name="options-outline" size={20} color={colors.moss} /></Pressable></View><View style={styles.filters}><Text style={styles.active}>Todos</Text><Text style={styles.filterText}>En tránsito</Text><Text style={styles.filterText}>Entregados</Text><Text style={styles.filterText}>Cancelados</Text></View>{deliveries.map((delivery) => <Pressable key={delivery.id} style={styles.card} onPress={() => delivery.status === 'En camino' ? router.push(`/seguimiento/${delivery.id}`) : router.push('/resumen-envio')}><View style={styles.icon}><Icon name={delivery.icon as any} size={22} color={colors.moss} /></View><View style={{ flex: 1 }}><View style={styles.line}><Text style={styles.cardTitle}>{delivery.id}</Text><Text style={[styles.status, { color: delivery.statusColor }]}>{delivery.status}</Text></View><Text style={styles.date}>{delivery.date} · {delivery.title}</Text><Text style={styles.route}>{delivery.from}  →  {delivery.to}</Text><View style={styles.line}><Text style={styles.transport}><Icon name="bicycle-outline" size={13} color={colors.moss} /> Bicicleta eléctrica</Text><Text style={styles.price}>{delivery.price}</Text></View></View><Icon name="chevron-forward" size={17} color="#A8B5AE" /></Pressable>)}</ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.cream }, content: { padding: 24, paddingTop: 64, paddingBottom: 35 }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, kicker: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.3 }, title: { color: colors.ink, fontSize: 29, fontWeight: '800', marginTop: 6 }, filter: { width: 43, height: 43, borderRadius: 14, backgroundColor: colors.mint, justifyContent: 'center', alignItems: 'center' }, filters: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 28, borderBottomWidth: 1, borderBottomColor: colors.line, paddingBottom: 12 }, active: { color: colors.moss, fontSize: 11, fontWeight: '800', borderBottomWidth: 2, borderBottomColor: colors.green, paddingBottom: 12, marginBottom: -13 }, filterText: { color: colors.muted, fontSize: 11 }, card: { backgroundColor: colors.white, borderRadius: 17, padding: 14, marginTop: 13, flexDirection: 'row', alignItems: 'center', gap: 11 }, icon: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.mint, justifyContent: 'center', alignItems: 'center' }, line: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, cardTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' }, status: { fontSize: 10, fontWeight: '800' }, date: { color: colors.muted, fontSize: 10, marginTop: 5 }, route: { color: colors.ink, fontSize: 12, marginTop: 6 }, transport: { color: colors.moss, fontSize: 10, marginTop: 9 }, price: { color: colors.ink, fontSize: 12, fontWeight: '800', marginTop: 9 } });
