/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/resumen-envio`; params?: Router.UnknownInputParams; } | { pathname: `/nuevo-envio`; params?: Router.UnknownInputParams; } | { pathname: `/repartidor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/envios` | `/envios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/seguimiento/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/resumen-envio`; params?: Router.UnknownOutputParams; } | { pathname: `/nuevo-envio`; params?: Router.UnknownOutputParams; } | { pathname: `/repartidor`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/envios` | `/envios`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/seguimiento/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/resumen-envio${`?${string}` | `#${string}` | ''}` | `/nuevo-envio${`?${string}` | `#${string}` | ''}` | `/repartidor${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/envios${`?${string}` | `#${string}` | ''}` | `/envios${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/resumen-envio`; params?: Router.UnknownInputParams; } | { pathname: `/nuevo-envio`; params?: Router.UnknownInputParams; } | { pathname: `/repartidor`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/envios` | `/envios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | `/seguimiento/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/seguimiento/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
